# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e1cd97e51dedcf6469a267bc85c31d82eb1a4ed17a65e5be3470438e0b55bf0592092e75e64811b66ee0e1ffe5ae7bb6bdc5ebcf80ea6bf1422ad32aae40fd9

test:
  secret_key_base: cfafd0780cd7e2c590fb7dc2dd9a4e3a6059416071cef2f6f449ed349b87d2c6cc50850f5b30d817ad073c337a7430ed6b33ed8e2f06a99d6267e832154a3934

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
